services:
  hardware_monitor:
    build: .
    container_name: hardware_monitor
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env
    volumes:
#      - ./data:/app/data
      - .:/app
    networks:
      - shared_net
    restart: unless-stopped
    command: ["gunicorn", "--reload", "-w", "4", "-b", "0.0.0.0:5000", "wsgi:app"]

networks:
  shared_net:
    external: true
